[Login]
# Tanpa TTY cadangan: Ctrl+Alt+F2 dst. tidak membuka konsol login.
NAutoVTs=0
ReserveVT=0
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
IdleAction=ignore
